CREATE TABLE project_github_repositories (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id     BIGINT       NOT NULL,
    github_repo_id BIGINT       NOT NULL,
    owner_login    VARCHAR(255) NOT NULL,
    repo_name      VARCHAR(255) NOT NULL,
    full_name      VARCHAR(255) NOT NULL,
    html_url       VARCHAR(500) NOT NULL,
    visibility     VARCHAR(20)  NOT NULL,
    linked_by      BIGINT       NOT NULL,
    linked_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_project_github_repositories_project UNIQUE (project_id),
    CONSTRAINT uq_project_github_repositories_github_repo UNIQUE (github_repo_id),
    CONSTRAINT fk_project_github_repositories_project FOREIGN KEY (project_id)
        REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT fk_project_github_repositories_linked_by FOREIGN KEY (linked_by)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_project_github_repositories_visibility CHECK (
        visibility IN ('PUBLIC', 'PRIVATE')
    )
);
