CREATE TABLE github_identities (
    user_id             BIGINT      NOT NULL,
    github_user_id      BIGINT      NOT NULL,
    github_login        VARCHAR(255) NOT NULL,
    connected_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_github_identities PRIMARY KEY (user_id),
    CONSTRAINT uq_github_identities_github_user UNIQUE (github_user_id),
    CONSTRAINT fk_github_identities_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE github_credentials (
    user_id                       BIGINT      NOT NULL,
    access_token_ciphertext       BYTEA       NOT NULL,
    encryption_key_version        VARCHAR(100) NOT NULL,
    created_at                    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_github_credentials PRIMARY KEY (user_id),
    CONSTRAINT fk_github_credentials_identity FOREIGN KEY (user_id)
        REFERENCES github_identities (user_id) ON DELETE CASCADE
);

ALTER TABLE project_github_repositories
    ADD CONSTRAINT uq_project_github_repositories_id_project UNIQUE (id, project_id);

CREATE TABLE github_contributions (
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id                    BIGINT       NOT NULL,
    project_github_repository_id  BIGINT       NOT NULL,
    user_id                       BIGINT,
    github_author_id              BIGINT,
    github_author_login           VARCHAR(255) NOT NULL,
    commit_sha                    VARCHAR(40)  NOT NULL,
    commit_url                    VARCHAR(500) NOT NULL,
    commit_message                TEXT         NOT NULL,
    committed_at                  TIMESTAMPTZ  NOT NULL,
    created_at                    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at                    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_github_contributions_repository_sha
        UNIQUE (project_github_repository_id, commit_sha),
    CONSTRAINT fk_github_contributions_project_repository
        FOREIGN KEY (project_github_repository_id, project_id)
        REFERENCES project_github_repositories (id, project_id) ON DELETE CASCADE,
    CONSTRAINT fk_github_contributions_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT ck_github_contributions_sha
        CHECK (commit_sha ~ '^[0-9a-f]{40}$')
);

CREATE INDEX ix_github_contributions_project_created
    ON github_contributions (project_id, committed_at DESC);
CREATE INDEX ix_github_contributions_user
    ON github_contributions (user_id) WHERE user_id IS NOT NULL;
CREATE INDEX ix_github_contributions_author
    ON github_contributions (github_author_id) WHERE github_author_id IS NOT NULL;

COMMENT ON COLUMN github_credentials.access_token_ciphertext IS
    'Application-encrypted GitHub OAuth token; decryption key is supplied outside the database.';
