ALTER TABLE users
    ADD COLUMN password_setup_required BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE password_setup_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL,
    token_hash  VARCHAR(64)  NOT NULL,
    purpose     VARCHAR(20)  NOT NULL,
    expires_at  TIMESTAMPTZ  NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_password_setup_tokens_hash UNIQUE (token_hash),
    CONSTRAINT fk_password_setup_tokens_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_password_setup_tokens_purpose CHECK (purpose IN ('INITIAL', 'RESET'))
);

CREATE INDEX ix_password_setup_tokens_user ON password_setup_tokens (user_id);
CREATE INDEX ix_password_setup_tokens_expiry ON password_setup_tokens (expires_at);

CREATE OR REPLACE FUNCTION fn_block_audit_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'audit_logs is append-only';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_audit_logs_no_update_or_delete
    BEFORE UPDATE OR DELETE ON audit_logs
    FOR EACH ROW EXECUTE FUNCTION fn_block_audit_mutation();

CREATE TRIGGER trg_audit_logs_no_truncate
    BEFORE TRUNCATE ON audit_logs
    FOR EACH STATEMENT EXECUTE FUNCTION fn_block_audit_mutation();
