-- V2: technical domains & scope assignments (module: domain)
-- domain_leads replaces blueprint's user_domains for DOMAIN_LEAD scope checks
-- (canManageDomain uses start_date/end_date term rows).

CREATE TABLE domains (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(50)  NOT NULL,
    description   VARCHAR(500),
    display_order INT          NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_domains_name UNIQUE (name)
);

CREATE TABLE domain_leads (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain_id   BIGINT NOT NULL,
    user_id     BIGINT NOT NULL,
    start_date  DATE   NOT NULL DEFAULT CURRENT_DATE,
    end_date    DATE,
    assigned_by BIGINT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_domain_leads_domain_user UNIQUE (domain_id, user_id),
    CONSTRAINT fk_domain_leads_domain FOREIGN KEY (domain_id)
        REFERENCES domains (id) ON DELETE CASCADE,
    CONSTRAINT fk_domain_leads_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_domain_leads_assigned_by FOREIGN KEY (assigned_by)
        REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT ck_domain_leads_date_range CHECK (end_date IS NULL OR end_date >= start_date)
);

CREATE INDEX ix_domain_leads_user ON domain_leads (user_id);

CREATE TABLE domain_members (
    domain_id  BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_domain_members PRIMARY KEY (domain_id, user_id),
    CONSTRAINT fk_domain_members_domain FOREIGN KEY (domain_id)
        REFERENCES domains (id) ON DELETE CASCADE,
    CONSTRAINT fk_domain_members_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE RESTRICT
);

CREATE INDEX ix_domain_members_user ON domain_members (user_id);
