-- V3: sessions & attendance (module: session; session owns attendance per mvp-feature-map)
-- Column names date/time kept faithful to blueprint section 10.

CREATE TABLE sessions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain_id   BIGINT      NOT NULL,
    program     VARCHAR(20) NOT NULL DEFAULT 'TECHNICAL',
    topic       VARCHAR(200) NOT NULL,
    type        VARCHAR(30) NOT NULL,
    date        DATE        NOT NULL,
    time        TIME        NOT NULL,
    description TEXT,
    objectives  TEXT[]      NOT NULL DEFAULT '{}',
    instructor  VARCHAR(100),
    lead_id     BIGINT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_sessions_domain FOREIGN KEY (domain_id)
        REFERENCES domains (id) ON DELETE RESTRICT,
    CONSTRAINT fk_sessions_lead FOREIGN KEY (lead_id)
        REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT ck_sessions_program CHECK (program IN ('TECHNICAL', 'FOUNDATION')),
    CONSTRAINT ck_sessions_type CHECK (
        type IN ('WORKSHOP', 'HACKATHON', 'TALK', 'SOCIAL', 'FOUNDATION')
    )
);

CREATE INDEX ix_sessions_domain_date ON sessions (domain_id, date);
CREATE INDEX ix_sessions_lead ON sessions (lead_id);

CREATE TABLE attendance (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT      NOT NULL,
    user_id    BIGINT      NOT NULL,
    status     VARCHAR(20) NOT NULL,
    marked_by  BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_attendance_session_user UNIQUE (session_id, user_id),
    CONSTRAINT fk_attendance_session FOREIGN KEY (session_id)
        REFERENCES sessions (id) ON DELETE CASCADE,
    CONSTRAINT fk_attendance_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_attendance_marked_by FOREIGN KEY (marked_by)
        REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT ck_attendance_status CHECK (
        status IN ('PRESENT', 'ABSENT', 'LATE', 'EXCUSED')
    )
);

CREATE INDEX ix_attendance_user ON attendance (user_id);
