-- V4: curated resource library & post-session tasks (modules: resource, task)
-- GitHub evidence: repo_url always stored; commit_sha format-checked at DB level,
-- Lead verify is a service action (verified/verified_by/verified_at).

CREATE TABLE resources (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT,
    domain_id  BIGINT       NOT NULL,
    title      VARCHAR(200) NOT NULL,
    url        VARCHAR(500) NOT NULL,
    type       VARCHAR(30)  NOT NULL,
    difficulty VARCHAR(20)  NOT NULL,
    topics     TEXT[]       NOT NULL DEFAULT '{}',
    quality    INT          NOT NULL DEFAULT 3,
    created_by BIGINT,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_resources_session FOREIGN KEY (session_id)
        REFERENCES sessions (id) ON DELETE CASCADE,
    CONSTRAINT fk_resources_domain FOREIGN KEY (domain_id)
        REFERENCES domains (id) ON DELETE RESTRICT,
    CONSTRAINT fk_resources_created_by FOREIGN KEY (created_by)
        REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT ck_resources_type CHECK (
        type IN ('DOCUMENTATION', 'COURSE', 'TUTORIAL', 'VIDEO', 'ARTICLE',
                 'PRACTICE_PLATFORM', 'GITHUB_REPO')
    ),
    CONSTRAINT ck_resources_difficulty CHECK (
        difficulty IN ('BEGINNER', 'INTERMEDIATE', 'ADVANCED')
    ),
    CONSTRAINT ck_resources_quality CHECK (quality BETWEEN 1 AND 5)
);

CREATE INDEX ix_resources_domain ON resources (domain_id);
CREATE INDEX ix_resources_session ON resources (session_id);

CREATE TABLE tasks (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id           BIGINT      NOT NULL,
    title                VARCHAR(200) NOT NULL,
    requirements         TEXT[]      NOT NULL DEFAULT '{}',
    deadline             TIMESTAMPTZ,
    verification_required BOOLEAN     NOT NULL DEFAULT FALSE,
    assignee_id          BIGINT,
    status               VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_tasks_session FOREIGN KEY (session_id)
        REFERENCES sessions (id) ON DELETE CASCADE,
    CONSTRAINT fk_tasks_assignee FOREIGN KEY (assignee_id)
        REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT ck_tasks_status CHECK (status IN ('OPEN', 'COMPLETED', 'VERIFIED'))
);

CREATE INDEX ix_tasks_session ON tasks (session_id);
CREATE INDEX ix_tasks_assignee ON tasks (assignee_id);

CREATE TABLE task_completions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id     BIGINT       NOT NULL,
    user_id     BIGINT       NOT NULL,
    repo_url    VARCHAR(500) NOT NULL,
    commit_sha  VARCHAR(40),
    notes       TEXT,
    verified    BOOLEAN      NOT NULL DEFAULT FALSE,
    verified_by BIGINT,
    verified_at TIMESTAMPTZ,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_task_completions_task_user UNIQUE (task_id, user_id),
    CONSTRAINT fk_task_completions_task FOREIGN KEY (task_id)
        REFERENCES tasks (id) ON DELETE CASCADE,
    CONSTRAINT fk_task_completions_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_task_completions_verified_by FOREIGN KEY (verified_by)
        REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT ck_task_completions_sha CHECK (
        commit_sha IS NULL OR commit_sha ~ '^[0-9a-f]{40}$'
    )
);

CREATE INDEX ix_task_completions_user ON task_completions (user_id);
