-- V5: project lifecycle, membership, work board, activity feed, discussions (module: project)
-- Single-table lifecycle (proposal fields live on projects) per blueprint 1.4.
-- activities is append-only: enforced in the database via trg_activities_no_update.

CREATE TABLE projects (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(150) NOT NULL,
    domain_id        BIGINT       NOT NULL,
    status           VARCHAR(30)  NOT NULL DEFAULT 'PROPOSED',
    program          VARCHAR(20)  NOT NULL DEFAULT 'TECHNICAL',
    problem          TEXT         NOT NULL,
    solution         TEXT         NOT NULL,
    technologies     TEXT[]       NOT NULL DEFAULT '{}',
    required_skills  TEXT[]       NOT NULL DEFAULT '{}',
    expected_members INT          NOT NULL DEFAULT 5,
    outcome          TEXT,
    created_by       BIGINT       NOT NULL,
    approved_by      BIGINT,
    review_comment   TEXT,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_projects_domain FOREIGN KEY (domain_id)
        REFERENCES domains (id) ON DELETE RESTRICT,
    CONSTRAINT fk_projects_created_by FOREIGN KEY (created_by)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_projects_approved_by FOREIGN KEY (approved_by)
        REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT ck_projects_status CHECK (
        status IN ('PROPOSED', 'UNDER_REVIEW', 'CHANGES_REQUESTED', 'APPROVED',
                   'ACTIVE', 'PAUSED', 'COMPLETED', 'ARCHIVED', 'REJECTED')
    ),
    CONSTRAINT ck_projects_program CHECK (program IN ('TECHNICAL', 'FOUNDATION')),
    CONSTRAINT ck_projects_expected_members CHECK (expected_members > 0)
);

CREATE INDEX ix_projects_status_domain ON projects (status, domain_id);
CREATE INDEX ix_projects_created_by ON projects (created_by);

CREATE TABLE project_members (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id  BIGINT      NOT NULL,
    user_id     BIGINT      NOT NULL,
    role        VARCHAR(20) NOT NULL DEFAULT 'MEMBER',
    status      VARCHAR(20) NOT NULL DEFAULT 'REQUESTED',
    reviewed_by BIGINT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_project_members_project_user UNIQUE (project_id, user_id),
    CONSTRAINT fk_project_members_project FOREIGN KEY (project_id)
        REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT fk_project_members_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_project_members_reviewed_by FOREIGN KEY (reviewed_by)
        REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT ck_project_members_role CHECK (role IN ('OWNER', 'MEMBER')),
    CONSTRAINT ck_project_members_status CHECK (
        status IN ('REQUESTED', 'ACTIVE', 'REJECTED')
    )
);

CREATE INDEX ix_project_members_user ON project_members (user_id);

CREATE TABLE work_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id  BIGINT       NOT NULL,
    title       VARCHAR(200) NOT NULL,
    assignee_id BIGINT,
    status      VARCHAR(20)  NOT NULL DEFAULT 'TODO',
    priority    VARCHAR(10)  NOT NULL DEFAULT 'MEDIUM',
    deadline    TIMESTAMPTZ,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_work_items_project FOREIGN KEY (project_id)
        REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT fk_work_items_assignee FOREIGN KEY (assignee_id)
        REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT ck_work_items_status CHECK (
        status IN ('TODO', 'IN_PROGRESS', 'BLOCKED', 'DONE')
    ),
    CONSTRAINT ck_work_items_priority CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH'))
);

CREATE INDEX ix_work_items_project_status ON work_items (project_id, status);

CREATE TABLE activities (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id   BIGINT,
    actor_id     BIGINT      NOT NULL,
    kind         VARCHAR(40) NOT NULL,
    text         TEXT        NOT NULL,
    evidence_ref VARCHAR(500),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_activities_project FOREIGN KEY (project_id)
        REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT fk_activities_actor FOREIGN KEY (actor_id)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_activities_kind CHECK (
        kind IN ('PROPOSAL_SUBMITTED', 'REVIEW_DECISION', 'JOIN_REQUESTED',
                 'MEMBER_JOINED', 'WORK_ITEM_CREATED', 'WORK_ITEM_DONE',
                 'TASK_COMPLETED', 'TASK_VERIFIED', 'PROJECT_STATUS_CHANGED')
    )
);

CREATE INDEX ix_activities_project_created ON activities (project_id, created_at);

CREATE TABLE messages (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT      NOT NULL,
    sender_id  BIGINT      NOT NULL,
    content    TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_messages_project FOREIGN KEY (project_id)
        REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT fk_messages_sender FOREIGN KEY (sender_id)
        REFERENCES users (id) ON DELETE RESTRICT
);

CREATE INDEX ix_messages_project_created ON messages (project_id, created_at);

-- Shared immutability guard, reused by xp_events (V6) and audit_logs (V7).
CREATE OR REPLACE FUNCTION fn_block_update() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'Table % is append-only: UPDATE is not allowed', TG_TABLE_NAME
        USING ERRCODE = 'restrict_violation';
END;
$$;

CREATE TRIGGER trg_activities_no_update
    BEFORE UPDATE ON activities
    FOR EACH ROW EXECUTE FUNCTION fn_block_update();
