-- V6: derived skill scores & gamification (modules: skill, gamification)
-- skills is a derived read model (weighted activity counts, no ML).
-- xp_events is an append-only ledger; the partial semantics of the UNIQUE
-- constraint (NULLs distinct) allow seed/manual XP without a ref.

CREATE TABLE skills (
    user_id    BIGINT NOT NULL,
    domain_id  BIGINT NOT NULL,
    score      INT    NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_skills PRIMARY KEY (user_id, domain_id),
    CONSTRAINT fk_skills_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_skills_domain FOREIGN KEY (domain_id)
        REFERENCES domains (id) ON DELETE CASCADE,
    CONSTRAINT ck_skills_score CHECK (score BETWEEN 0 AND 100)
);

CREATE INDEX ix_skills_domain_score ON skills (domain_id, score DESC);

CREATE TABLE xp_events (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL,
    amount     INT         NOT NULL,
    source     VARCHAR(30) NOT NULL,
    ref_type   VARCHAR(30),
    ref_id     BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_xp_events_user_source_ref UNIQUE (user_id, source, ref_type, ref_id),
    CONSTRAINT fk_xp_events_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_xp_events_source CHECK (
        source IN ('SESSION', 'RESOURCE', 'TASK', 'MENTORING', 'PR_MERGED',
                   'CONTRIBUTION', 'PROJECT_DONE')
    ),
    CONSTRAINT ck_xp_events_amount CHECK (amount > 0)
);

CREATE INDEX ix_xp_events_user_created ON xp_events (user_id, created_at);

CREATE TABLE achievements (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(50)  NOT NULL,
    name        VARCHAR(100) NOT NULL,
    description TEXT,
    rule        TEXT         NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_achievements_code UNIQUE (code)
);

CREATE TABLE user_achievements (
    user_id        BIGINT      NOT NULL,
    achievement_id BIGINT      NOT NULL,
    earned_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_user_achievements PRIMARY KEY (user_id, achievement_id),
    CONSTRAINT fk_user_achievements_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_achievements_achievement FOREIGN KEY (achievement_id)
        REFERENCES achievements (id) ON DELETE CASCADE
);

CREATE INDEX ix_user_achievements_achievement ON user_achievements (achievement_id);

CREATE TRIGGER trg_xp_events_no_update
    BEFORE UPDATE ON xp_events
    FOR EACH ROW EXECUTE FUNCTION fn_block_update();
