-- V7: DB-backed notifications (poll 30s) & append-only audit trail (modules: notification, audit)

CREATE TABLE notifications (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL,
    kind       VARCHAR(40) NOT NULL,
    title      VARCHAR(150) NOT NULL,
    body       TEXT,
    link       VARCHAR(300),
    read       BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_notifications_kind CHECK (
        kind IN ('TASK_ASSIGNED', 'TASK_VERIFIED', 'JOIN_REQUESTED', 'JOIN_APPROVED',
                 'WORK_ITEM_ASSIGNED', 'PROJECT_STATUS_CHANGED',
                 'ACHIEVEMENT_UNLOCKED', 'SYSTEM_ANNOUNCEMENT')
    )
);

CREATE INDEX ix_notifications_user_created ON notifications (user_id, created_at);
CREATE INDEX ix_notifications_user_unread ON notifications (user_id, created_at)
    WHERE NOT read;

CREATE TABLE audit_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id    BIGINT,
    action      VARCHAR(50) NOT NULL,
    resource    VARCHAR(50),
    resource_id BIGINT,
    result      VARCHAR(20) NOT NULL DEFAULT 'SUCCESS',
    meta        JSONB,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_audit_logs_actor FOREIGN KEY (actor_id)
        REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT ck_audit_logs_result CHECK (result IN ('SUCCESS', 'FAILURE'))
);

CREATE INDEX ix_audit_logs_created ON audit_logs (created_at DESC);
CREATE INDEX ix_audit_logs_actor ON audit_logs (actor_id);
CREATE INDEX ix_audit_logs_action ON audit_logs (action);

CREATE TRIGGER trg_audit_logs_no_update
    BEFORE UPDATE ON audit_logs
    FOR EACH ROW EXECUTE FUNCTION fn_block_update();
